CREATE DATABASE IF NOT EXISTS ES05;
USE ES05;

DROP USER IF EXISTS ES05_user;
CREATE USER IF NOT EXISTS ES05_user IDENTIFIED BY 'mia_password';
GRANT SELECT, INSERT, UPDATE, DELETE ON ES05.* TO ES05_user;

CREATE TABLE IF NOT EXISTS account(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

insert into account (id,username, password)
VALUES (NULL, 'admin', 'prova');
